title: Jonas Blatter
description: Personal Website
logo: https://avatars2.githubusercontent.com/u/14215958
markdown: kramdown


collections:
  categories:
    output: true
  category:
    output: true
