title: Personal Website
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: jonasblatter
url: https://jonasblatter.github.io/

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

collections:
  category:
    output: true

titles_from_headings:
  strip_title: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jonas Blatter"
  avatar : "https://avatars2.githubusercontent.com/u/14215958"
  bio    : "PostDoc researcher in ethics, emotion, and digital technology."
  links:
    - label: "PhilPeople"
      icon: "fas fa-fw fa-link"
      url: "https://philpeople.org/profiles/jonas-blatter"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/blatterjo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonasblatter/"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://zirk.us/@jonasblatter/"

footer:
  links:
    - label: "PhilPeople"
      icon: "fas fa-fw fa-link"
      url: "https://philpeople.org/profiles/jonas-blatter"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/blatterjo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jonasblatter/"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://zirk.us/@jonasblatter/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
