title: Jonas Blatter
logo: https://avatars2.githubusercontent.com/u/14215958
markdown: kramdown

defaults:
  - scope:
    path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
