title: Jonas Blatter
description: Personal Website
logo: https://avatars2.githubusercontent.com/u/14215958
markdown: kramdown
url: https://jonasblatter.github.io/

collections:
  category:
    output: true
